import React from 'react'
import Head from "next/head"

import s from './page.module.scss'
import Header from "../../common/Header/Header"

const Page = props => {
  return (
    <>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app"/>
      </Head>

      <Header/>

      <main className={s.main}>
        <div className="container">
          {props.children}
        </div>
      </main>
    </>
  )
}

export default Page
