import React from 'react'
import Head from "next/head"
import {Fade} from "react-awesome-reveal"

import s from './page.module.scss'

import Header from "../../common/Header/Header"
import AppDescr from "../../common/AppDescr/AppDescr"
import Footer from "../../common/Footer/Footer"

const Page = props => {
  return (
    <>
      <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app"/>
      </Head>

      <Header/>

      <main className={s.main}>
        <div className="container">
          {props.children}
        </div>

        {props.homePage && <Fade><AppDescr/></Fade>}

      </main>

      <Footer/>
    </>
  )
}

export default Page
