import Head from 'next/head'

import React from 'react'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
      </Head>
    </div>
  )
}

export default Home
